Dockerfile: run entrypoint as root
Since 492b2c56abfc, the entrypoint is executed as 'builder' user.
Therefore, using a USER_ID and GROUP_ID currently fails:
groupmod: Permission denied.
groupmod: cannot lock /etc/group; try again later.
usermod: group '1000' does not exist
chown: changing ownership of '/builder/.bash_logout': Operation not permitted
chown: changing ownership of '/builder/.profile': Operation not permitted
chown: changing ownership of '/builder/.bashrc': Operation not permitted
chown: changing ownership of '/builder': Operation not permitted
error: failed switching to "builder": operation not permitted

As the entrypoint is designed to be executed as root, revert it back.

Signed-off-by: Benjamin Bara <benjamin.bara@skidata.com>